projects:
  lasvittennis:
    schemaPath: graphql/schema.json
    includes:
      - modules/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: modules/graphql
extensions:
  amplify:
    version: 3
